server:
  port: 9093
  address: 10.10.50.232
spring:
  profiles: test
  redis:
    database: 4
    host: 10.10.50.232
    port: 6379
    timeout:  8000
    password: neotvredis
    pool:
      max-wait: 5000
      max-active: 100
  application:
    name: cn.dianjingquan.zoo.api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.50.232:3306/zoo?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: neotvmysql
    #url: jdbc:mysql://rdsanqi6zanqi6zpublic.mysql.rds.aliyuncs.com/djq_match?autoReconnect=true&useSSL=false
    #username: "ees_test"
    #password: "djq-EES_2016!@#"
  data:
      jpa:
        repositories:
          enabled: true
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: update
  cloud:
    consul:
      enabled: true
      host: 10.10.50.232
      port: 8500
      discovery:
        enabled: true
        healthCheckInterval: 20s
        instanceId: zoo_service_instance_1
        serviceName: zoo_service
        tags: dev
        health-check-url: http://${spring.cloud.consul.host}:${server.port}/health
        #health-check-url: http://10.10.30.131:9020/health

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.10.50.232:8761/eureka/
#    instance:
#      preferIpAddress: true