server:
  port: 9093
  address: 10.25.172.250
spring:
  profiles: prod
  redis:
    database: 4
    host: 10.25.173.114
    port: 6379
    timeout:  8000
    password: neotvredis
    pool:
      max-wait: 5000
      max-active: 100
  application:
    name: cn.dianjingquan.zoo.api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dianjingquan.mysql.rds.aliyuncs.com/m_djq_zoo?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ees_root
    password: djq@NEOTV#2016!
  data:
      jpa:
        repositories:
          enabled: true
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: update
  cloud:
    consul:
      enabled: true
      host: 10.25.172.250
      port: 8500
      discovery:
        enabled: true
        healthCheckInterval: 20s
        instanceId: zoo_service_instance_1
        serviceName: zoo_service
        tags: prod
        health-check-url: http://${spring.cloud.consul.host}:${server.port}/health